resources:
  - ../../base

configMapGenerator:
  - name: orgfin-env
    envs:
      - .env.prod

replacements:
  - source:
      kind: ConfigMap
      name: orgfin-env
      fieldPath: data.HOSTNAME
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.host

patches:
  - target:
      version: v1
      kind: Ingress
      name: orgfin-ingress
    path: ingress-patch.yaml

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: orgfin-celery
    path: command-celery-patch.yaml

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: orgfin-beat
    path: command-beat-patch.yaml