- op: replace
  path: /spec/rules/0/http/paths
  value:
    - path: /auth
      pathType: Prefix
      backend:
        service:
          name: backend-go
          port:
            number: 8001
    - path: /accounts
      pathType: Prefix
      backend:
        service:
          name: backend-go
          port:
            number: 8001
    - path: /categories/grouped
      pathType: Prefix
      backend:
        service:
          name: backend
          port:
            number: 8000
    - path: /categories
      pathType: Prefix
      backend:
        service:
          name: backend-go
          port:
            number: 8001
    - path: /currencies
      pathType: Prefix
      backend:
        service:
          name: backend-go
          port:
            number: 8001
    - path: /users
      pathType: Prefix
      backend:
        service:
          name: backend-go
          port:
            number: 8001
    - path: /transactions
      pathType: Prefix
      backend:
        service:
          name: backend-go
          port:
            number: 8001
    - path: /
      pathType: Prefix
      backend:
        service:
          name: backend
          port:
            number: 8000
