resources:
  - ../../base

configMapGenerator:
  - name: orgfin-env
    envs:
      - .env

replacements:
  - source:
      kind: ConfigMap
      name: orgfin-env
      fieldPath: data.HOSTNAME
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.host
